# Generated by Django 2.1 on 2019-01-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an ordering party (e.g. General, Anesthesia)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('priceUnit', models.CharField(max_length=10)),
                ('actualPrice', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('minQty', models.IntegerField()),
                ('stockQty', models.IntegerField()),
                ('unitQty', models.CharField(max_length=5)),
                ('orderQty', models.IntegerField()),
                ('comments', models.TextField(blank=True, help_text='OPTIONAL: Enter Comments', max_length=300)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Vendor (e.g. MCKESSON, SCHEIN)', max_length=20)),
            ],
        ),
    ]
