# Generated by Django 2.1 on 2019-01-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actualPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minQty',
            field=models.IntegerField(help_text='Enter minimum quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='orderQty',
            field=models.IntegerField(blank=True, help_text='OPTIONAL: Enter quantity to order', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stockQty',
            field=models.IntegerField(help_text='Enter current quantity in stock'),
        ),
    ]
